### ISSUE TITLE
yarock: no audio engine loaded

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#11]
![Screenshot_20190710_200825](https://user-images.githubusercontent.com/840070/61001237-c0447800-a34e-11e9-8a9b-831744035421.png)

**Comment by llelectronics** [comment]
@ScarlettGatelyMoore I think yarock needs a recompile. I cannot get the phonon engine (the only one we ship [yes we build this app] to work)

**Comment by ScarlettGatelyMoore** [comment]
I can reproduce this, I am trying to work it out, the plugin is installed and available in settings but doesn't work.

**Comment by ScarlettGatelyMoore** [comment]
Ok, apparently it doesn't like multiarch. This is now fixed

**Comment by Mackel123** [comment]
No, when I choose vlc or mpv, it told no audio engine loaded.

**Comment by star-buck** [comment]
Which version?

**Comment by Mackel123** [comment]
### **the version of yarock:**
Repository     : Additional packages maintained by the KDE team (openSUSE_Tumbleweed)
Name           : yarock                                                              
Version        : 1.4.0-5.29                                                          
Arch           : x86_64                                                              
Vendor         : obs://build.opensuse.org/KDE:Extra                                  
Installed Size : 2.8 MiB                                                             
Installed      : Yes                                                                 
Status         : up-to-date                                                          
Source package : yarock-1.4.0-5.29.src                                               
Summary        : Qt5 Music Player 

### **the version of vlc**
`Repository    : @System                      
Name           : vlc                          
Version        : 3.0.8-7.5                    
Arch           : x86_64                       
Vendor         : http://packman.links2linux.de
Installed Size : 1.8 MiB                      
Installed      : Yes                          
Status         : up-to-date                   
Source package : vlc-3.0.8-7.5.src            
Summary        : Graphical media player`

### **the version of mpv:**
Repository     : Main Repository (OSS)                            
Name           : mpv                                              
Version        : 0.32.0+git.20200213T013258.5bf433b16f-1.1        
Arch           : x86_64                                           
Vendor         : openSUSE                                         
Installed Size : 2.3 MiB                                          
Installed      : Yes                                              
Status         : up-to-date                                       
Source package : mpv-0.32.0+git.20200213T013258.5bf433b16f-1.1.src
Summary        : Advanced general-purpose multimedia player

### * My susterm*
Linux version 5.5.2-1-default (geeko@buildhost) 
(gcc version 9.2.1 20200128 [revision 83f65674e78d97d27537361de1a9d74067ff228d] (SUSE Linux)) 
1 SMP Sat Feb 8 07:54:02 UTC 2020 (994cf1f)

### **the version of qt**

Operating System: openSUSE Tumbleweed 20200214
KDE Plasma Version: 5.18.0
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.5.2-1-default
OS Type: 64-bit
Processors: 6 × Intel® Core™ i5-9400F CPU @ 2.90GHz
Memory: 7.7 GiB of RAM

**Comment by star-buck** [comment]
Oh, you're not using Netrunner? We know that distros need to ship a proper
audio engine, hence we configured it on debian stable ootb for Netrunner
19.08 and upcoming 20.01. Now for openSuse, this might be similar, but you
need to look / ask there how to get it working properly. If we have an
idea, we will certainly help you though, just closing this here again since
its Netrunner ticket system.

**Comment by star-buck** [comment]
here is a screenshot, we use neither vlc nor mpv, but phonon:
![Screenshot_20200217_171958](https://user-images.githubusercontent.com/840070/74674888-36913e80-51aa-11ea-8128-01670e1aecc3.png)

**Comment by star-buck** [comment]
![Screenshot_20200217_172441](https://user-images.githubusercontent.com/840070/74674984-722c0880-51aa-11ea-86cf-f99d6aafcb31.png)

**Comment by star-buck** [comment]
@Mackel123 : how does your yarock Engine settings look like?

**Comment by Mackel123** [comment]
> here is a screenshot, we use neither vlc nor mpv, but phonon:
> ![Screenshot_20200217_171958](https://user-images.githubusercontent.com/840070/74674888-36913e80-51aa-11ea-8128-01670e1aecc3.png)

Me too but I don't know wich engine is better to listen music…

**Comment by Mackel123** [comment]
![image](https://user-images.githubusercontent.com/27003282/74675208-04a1cb80-51ee-11ea-82ff-2c139148924e.png)
