### ISSUE TITLE
shutdown: netrunner never fully shuts down, there is always the power light button and the fan running

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#29]
we had this before and then fixed it a few versions ago.

**Comment by llelectronics** [comment]
This one was a bit harder to fix. But thanks to Harald I found out that touching the font for plymouth helps to load it into cache and such the shutdown is working as expected
This commit hopefully fixes the issue for you too: https://github.com/ds9-common/default-settings-systemd/commit/feb45e52153f04352980d1a4a9777feba61ddea1

**Comment by star-buck** [comment]
What the heck :)

**Comment by star-buck** [comment]
still doesnt work here

**Comment by llelectronics** [comment]
Sorry my mistake. The systemd service file installs fine but is not activated by default. This commit should fix it now. Lets have debhelper take care of writing the correct stuff with dh_systemd 
https://github.com/ds9-common/default-settings-systemd/commit/2c5eef9ca8f0285807751c55dcf32245a108a19c

**Comment by llelectronics** [comment]
Shutdown works for me in live and after installation on **netrunner-20190805.0503**
