### ISSUE TITLE
Samba shares or samba mounter: does not find any workgroup, place is empty

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#40]

**Comment by ScarlettGatelyMoore** [comment]
I dusted off an old windows partition to try and figure this one out, but can't seem to find any program called samba shares or samba mounter. It says it is installed but I can't sort how to use it and can find no docs. I don't use windows enough to help here yet :(

**Comment by ScarlettGatelyMoore** [comment]
well smb4k does show my MOORE workgroup but I can't get any combination of username password to work.

**Comment by star-buck** [comment]
Thats weird. Ill test again with next image.

**Comment by ScarlettGatelyMoore** [comment]
I can see my shares when I use smb:\\my.ip.address but I still epic-ally fail with username and password. I have tried local account and microsoft account to no avail. I don't get it. I am giving up for today. Maybe @llelectronics will do better.

**Comment by star-buck** [comment]
there is definately something broken between now and a few ISOs back.
smb:// shows nothing when pressing open button:
![Screenshot_20190815_092336](https://user-images.githubusercontent.com/840070/63086043-87478680-bf3e-11e9-974e-451ca95989d4.png)
also Network or Shared folders is empty:
![Screenshot_20190815_092559](https://user-images.githubusercontent.com/840070/63086160-c1188d00-bf3e-11e9-867f-a8e7a88a887a.png)

**Comment by star-buck** [comment]
i googled and tried to use a fix to add a line in smb.conf:
![Screenshot_20190815_093048](https://user-images.githubusercontent.com/840070/63086676-e5289e00-bf3f-11e9-9abd-e05349e42156.png)
this brought back showing workgroup again when clicking on samba shares from network in dolphin, but clicking that then ended in an error:
![Screenshot_20190815_093353](https://user-images.githubusercontent.com/840070/63086744-0be6d480-bf40-11e9-8969-1f5930bfa188.png)
![Screenshot_20190815_093408](https://user-images.githubusercontent.com/840070/63086747-0db09800-bf40-11e9-956c-7714c5c5abf5.png)

**Comment by star-buck** [comment]
smbtree works fine:
![Screenshot_20190815_093850](https://user-images.githubusercontent.com/840070/63086959-87488600-bf40-11e9-8c36-24cd72a94162.png)

**Comment by llelectronics** [comment]
Weird indeed. On my test machines I cannot reproduce it. All samba shares appear fine and are accessible. (Though I don't have a Windows machine to test) 

![Screenshot_20190815_114631](https://user-images.githubusercontent.com/3415572/63087565-cbdd1d00-bf52-11e9-9561-22d4cb447e8a.png)

**Comment by star-buck** [comment]
thats really weird... i mean i need to set this nt1 option explicitly to see workgroups, but then it still fails. 

but entering smb://workgroup/tx110/ in samba mounter does work!

**Comment by star-buck** [comment]
i wonder what has changed in the last 4-5 isos?

**Comment by star-buck** [comment]
basically what throws the error is:
smb:///  with three slashes doesnt get you results, but an error. smb:// with two slashes shows you workgroup, but only after setting the line in smb.conf

**Comment by star-buck** [comment]
this is really weird, now getting this:
![Screenshot_20190815_124016](https://user-images.githubusercontent.com/840070/63089940-e8c91e80-bf59-11e9-88e6-5556b9388a64.png)

**Comment by star-buck** [comment]
i suspect something is weird over here, need to actually check if my router changed something or whatever happened...

**Comment by star-buck** [comment]
lets consider this on my end
