### ISSUE TITLE
Plasma Services: module switches appearances broken 

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#42]
![Screenshot_20190815_091627](https://user-images.githubusercontent.com/840070/63085824-fb355f00-bf3d-11e9-8c00-d82bf63f5422.png)

**Comment by llelectronics** [comment]
Has something to do with Kvantum theme I fear.

**Comment by star-buck** [comment]
true. can you check if we can target it to not use kvantum, i think there are some options to allow a list of non-targets, maybe even whole systemsettings

**Comment by ScarlettGatelyMoore** [comment]
Reproducible here. Trying to find a solution.

**Comment by star-buck** [comment]
Its kvantum theme, going to breeze fixes it. Maybe finding a more common
element in source code would fix it.
