### ISSUE TITLE
kwin stuttering and framedrops: intel and ati

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#47]
this describes it pretty well, even without that testsite, the mouse is not stablelized and stutters as soon as i move it a bi faster around:
https://www.youtube.com/watch?v=iDG_yiqL5CQ

testsite:
https://www.vsynctester.com/
----
intel i915, modesetting
trying various things:
GL_YIELD=USLEEP in /etc/profile.d/kwin.sh

FF: about:config and set layers.acceleration.force-enabled

https://www.pcsuggest.com/fix-linux-screen-tearing/

> Section "Device"
> Identifier "Intel Graphics"
> Driver "intel"
> Option "DRI" "2"
> Option "AccelMethod" "SNA"
> Option "TripleBuffer" "true"
> option "TearFree" "true"
> EndSection

**Comment by ScarlettGatelyMoore** [comment]
I have nvidia and have same thing.

**Comment by star-buck** [comment]
i wonder if we have any setting active like triple buffer or else set that leads to this.
Or if trying such things would mitigate it.
@llelectronics : do you know if we already do anything in netrunner, since this happened in the past always once in a while?

**Comment by llelectronics** [comment]
Nothing I am aware of in our current configuration.
