### ISSUE TITLE
FF: about:config: set layers.acceleration.force-enabled to true

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#50]
https://www.reddit.com/r/linux/comments/662dxm/psa_hardware_acceleration_on_firefox_may_be/

**Comment by star-buck** [comment]
its an idea, we would need to test it on rock64, so i will try that next

**Comment by llelectronics** [comment]
In general Netrunner I would not want to enable this as it causes crashes on some hardware.
