### ISSUE TITLE
repos: testing entry should be above buster-backports ?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#53]
![Screenshot_20190820_131716](https://user-images.githubusercontent.com/840070/63343740-feba5300-c34e-11e9-9d9e-28e0a4e3c9cc.png)

**Comment by llelectronics** [comment]
Unfortunately I don't see a way to control how synaptic will list it in its editor.

**Comment by star-buck** [comment]
Hasnt this to do with priority?

**Comment by llelectronics** [comment]
Apt pinning has nothing to do with it actually.

**Comment by star-buck** [comment]
I always thought that the order had an influence on what gets selected (not
via pinning):
https://askubuntu.com/a/153408

**Comment by llelectronics** [comment]
No the order that synaptic lists them has no influence afaik.

**Comment by star-buck** [comment]
Why would there by an up and down button then? Imo this change has an
effect, its not there just for fun.

**Comment by ScarlettGatelyMoore** [comment]
It will always come down to versions of each individual package. Listing of repos order has no affect.

**Comment by ScarlettGatelyMoore** [comment]
Unless of course the distro sets priority via apt pinning ( we don't ). This is the exact reason I couldn't use apt pinning for the font issue.
