### ISSUE TITLE
fix "Netrunner Black" to switch color theme also to something that looks dark

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#54]
Not sure what we forgot to set in Dark LNF:
https://youtu.be/_keWdXD8S1g?t=234

**Comment by star-buck** [comment]
the question is if we respin the package we should move it into our own backports repo, so people get it updated or directly in the main repo?

**Comment by llelectronics** [comment]
After first check. The issue is not with our color scheme the as it gets selected normally. The issue is with the kvantum file. It ignores all color schemes and sets its own colors apparently.

**Comment by star-buck** [comment]
Can we either set a different Kvantum theme via LNF or if not, set Widget
engine to Breeze?

**Comment by ScarlettGatelyMoore** [comment]
Oh. It is because in order for it to be default it was set in .skel to be copied over in .config. This is set in a common package. I think we need to have .skel to be per type eg: dekstop/core etc. This hasn't been an issue before?

**Comment by llelectronics** [comment]
@ScarlettGatelyMoore not sure what you mean. But no this is not an issue we had before. I thought the widget theming engine is set in our LNF. Only thing we set is the kvantum theme file itself which only affects Desktop as Core does not use it.

**Comment by llelectronics** [comment]
IMHO this in the kvantum file is the problem: https://github.com/netrunner-artwork/artwork-lnf-theme-netrunner-indigo/blob/Netrunner/19.08/usr/share/Kvantum/KvIndigo2/KvIndigo2.kvconfig#L76

The whole section prevents it from taking over the colors set in color-scheme

**Comment by ScarlettGatelyMoore** [comment]
Ahh, but that isn't something I set, is it? Where do they go? isn't there a theme .colors file?

**Comment by llelectronics** [comment]
No it isn't. It is the part of the kvantum theme file itself. See above. I suspect them to be there since the beginning. Testing it right now reveals it does not fix everything. Colors for buttons and tabs are wrong. (text color that is)

**Comment by llelectronics** [comment]
For now it seems Kvantum does not support the "native" color schemes fully. I would suggest to switch to BreezeDark then for the Netrunner Black LNF as LNFs cannot write and apply a different Kvantum Theme (which would also fix the issue)

**Comment by star-buck** [comment]
Yes, lets do that.
