### ISSUE TITLE
start prepare everything for a netrunner-20.01 alpha iso

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#57]
- update all packages
- change version number, change version name to tbd

**Comment by star-buck** [comment]
actually do the first alpha iso also for desktop 64bit of course

**Comment by llelectronics** [comment]
First ISO ready: https://ds9-eu.s3.eu-central-1.amazonaws.com/dci/images/next/amd64/netrunner-desktop/jobs/img_desktop_netrunner-desktop_next_amd64/222/netrunner-20191120.1857-amd64.hybrid.iso

**Comment by llelectronics** [comment]
Just for reference. The newest ISOs can be found here: https://dci.netrunner.com/view/Images/view/Netrunner%20Next%20Images/view/Netrunner%20Desktop%20AMD64/view/All/job/img_desktop_netrunner-desktop_next_amd64/
