### ISSUE TITLE
live/installed grub: add timer so it starts selected entry automatically after e.g. 10 seconds

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#59]

**Comment by llelectronics** [comment]
After install grub has a 5 second timeout. 
I will add this to the live configs aswell.

**Comment by star-buck** [comment]
Please increase the timer to 10 seconds for both live and also after install.
Currently the timer when starting from live has been descreased to be almost impossible to select (i couldnt even read it, it may have been 5 seconds but the timer already run out before the selection screen was shown, which on the same machine was different (10 seconds) in the past).

**Comment by star-buck** [comment]
is this on the latest ISO?

**Comment by star-buck** [comment]
I downloaded the latest ISO and wondering what actually has been fixed...

**Comment by star-buck** [comment]
@llelectronics : this is still not fixed?

**Comment by ScarlettGatelyMoore** [comment]
Looks like it wasn't merged, done now

**Comment by ScarlettGatelyMoore** [comment]
Nope, it was merged. Needs further investigation.

**Comment by llelectronics** [comment]
Fixed the isolinux.cfg which strangely divides the timeout you define by 10 so setting 100 sets a 10 second timeout for isolinux now correctly
