### ISSUE TITLE
Netrunner 20.01 - Twenty - Release Todos

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#60]
- update link to mycroft plasma: https://www.blue-systems.com/projects/
- links to kaccounts
- links to kio-fuse

If you ever hit broken packages message try to fix with this:
"sudo dpkg –configure -a"

sudo apt upgrade
sudo apt dist-upgrade could make your system unstable or even break it completely

update debian testing screenshots

based on Debian Stable 10.3 (buster)

-----

Codename will by "Twenty", since it is actually the twentieth release since Netrunner 1 (not counting Maui nor Rolling nor point releases).

- [x] change codename to "Twenty"
- [x] change versioning to Netrunner 20.01
- [x] repos: change netrunner-next to netrunner-20.01
-----
- [x] remove LNF Netrunner Blue
- [x] remove Splash Blue (doesnt work and crashes ksplash)
-----
- [x] LNF Indigo:
- [x] change Window Deco to Breeze
- [x] FX: TURN ON magic lamp

------
Wallpaper will be posted here as soon as i got it (see other ticket)

**Comment by star-buck** [comment]
Why does the latest ISO show NETRUNNER INDIGO AGAIN?

**Comment by ScarlettGatelyMoore** [comment]
Looks like something went wrong on last ISO, looking into it

**Comment by llelectronics** [comment]
Issue was the branches where not synced up. Master was not merged into 20.01.
I fixed that for some packages already like base-files and calamares branding and changed some stuff that wasn't yet.

**Comment by ScarlettGatelyMoore** [comment]
Removed LNF Blue across all releases. I noticed a     - desktop-theme-bluex:
        branch: Netrunner/20.01 entry as well, do these need removal? or just the LNF?


I also noticed that the other Splash options ( including Indigo ) are empty/broken because they are not configured in the LNF package. Example: https://github.com/netrunner-artwork/artwork-lnf-theme-netrunner-indigo/tree/master/usr/share/plasma/look-and-feel/org.kde.netrunner-indigo.desktop/contents/splash only has an empty QML file. It would be better to just remove the directory all together to clean up the Splash Screen system settings, as selecting the option changes nothing.

**Comment by ScarlettGatelyMoore** [comment]
![Screenshot_20200116_101931](https://user-images.githubusercontent.com/1056501/72547804-95316880-384a-11ea-932d-6089440cd81f.png)

**Comment by llelectronics** [comment]
The qml should not be emtpy in the LNF but have an empty Item as this is the only way to skip ksplash which we want.

**Comment by llelectronics** [comment]
Update: Fixed bluex lnfs splash screen: https://github.com/ds9-artwork/lnf-theme-bluex/commit/4146e587f61301943ba592b92698b48a30028f9d

**Comment by ScarlettGatelyMoore** [comment]
> The qml should not be emtpy in the LNF but have an empty Item as this is the only way to skip ksplash which we want.

Oh ok.
