### ISSUE TITLE
upstream: update appimagelauncher

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#61]
update tolatest version and see if these settings are matching:

- fix "updater unavailable" message (ask Fabian)
- TICK "ask wether to move the..."
- path should be "~/Applications" (ask Fabian if this works or how to achieve this if necessary)

it seems the defaults would be the above settings, but not sure if that is just recently or changed

**Comment by ScarlettGatelyMoore** [comment]
This is sadly stuck on the debian side, I will put my packaging on DCI
