### ISSUE TITLE
vokoscreen: doesnt seem to start recording

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#63]

**Comment by ScarlettGatelyMoore** [comment]
vokoscreenversion in Debian is no longer maintained upstream, they have moved to vokoscreenNG. I will work on packaging it for netrunner and future debian.

**Comment by star-buck** [comment]
Okay. Please see to get it ready for next week, otherwise we need to ship
an alternative.

**Comment by star-buck** [comment]
@ScarlettGatelyMoore : is this shipped in next iso?

**Comment by llelectronics** [comment]
Vokoscreen is working fine for me. It records the desktop in its default settings just fine. 
Just the tray icon does not change to pause+stop anymore. So you need to right click to stop recording. But recording works just fine.

**Comment by star-buck** [comment]
It doesnt seem to if you scale to something different than 1.0?

**Comment by llelectronics** [comment]
Scale inside of Plasma? Or how do you scale in vokoscreen? 
Scaling in Plasma set to 1.2 and it still works:
https://cloud.opendesktop.org/f/120297

**Comment by star-buck** [comment]
Display kcm, scaled to 1.5 doesnt start recording here.
Kazam works fine, as does simplescreenrecorder. Maybe we should switch to
one or the other?

**Comment by llelectronics** [comment]
1.5 also works for me. I wonder if its something hardware specific like a driver issue. Do you have any output?
https://youtu.be/gIKeqtMds-I

**Comment by star-buck** [comment]
Im not at any computer for the next times, so unfortunately no.
