### ISSUE TITLE
Virtualbox missing / not packaged in Debian Stable. What to do?

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-next#66]
Virtualbox from our checkbox is not packaged in Debian Stable. 
There is a version in Debian Sid which is not compatible with stable though. 

2 ways to fix this:

**1)** Rebuild the Debian Sid image on DCI   
*Pros:* familiarity for users
*Cons:* we have to maintain it e.g. security updates, dci, solve potential issues

**2)** We use an alternative like *aqemu*
*Pros:* maintained by debian, kvm is actually faster and more compatible with linux
*Cons:* a bit unknown to users, less translations for the GUI

**Comment by ScarlettGatelyMoore** [comment]
Yeah, it is no longer available in stable :( I have tried a few alternatives and none have made me excited. I am currently running one of my setups with sid repos enabled and no problems so far. It is overhead to carry though.

**Comment by star-buck** [comment]
Is there a flatpak of vbox? But that may mean an enormous overhead of +1GB
on the iso with all the base layer(s).

**Comment by llelectronics** [comment]
I never saw a flatpak of Virtualbox as it is not possible as it needs to generate some kernel modules on installation.

**Comment by star-buck** [comment]
aqemu is confusing, old and unfortunately even crashed when trying to add a storage :/

trying virt-manager now as gui frontend, looks okay so far, but still needs testing.
@llelectronics @ScarlettGatelyMoore : please try virt-manager yourself and report back on your impression and if its working for you.

**Comment by ScarlettGatelyMoore** [comment]
That is what I was using before I added sid repos for virtualbox. It is not terrible, but it isn't virtualbox. It does work though.
