### ISSUE TITLE
Samba Mounter shows fails to mount smb shares (Bad UNC) but mounts correctly

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-next#68]
I fail to seet why I get a mount error when mounting my samba shares which work fine with kio-smb. 
Strange thing besides this error message it mounts correctly after a few seconds and the folder in Networks works like it should. 

![image](https://user-images.githubusercontent.com/3415572/72227744-482a6980-35a0-11ea-8939-700a1e995b58.png)

**Comment by star-buck** [comment]
Looks like because of the "ö" .

**Comment by llelectronics** [comment]
Tried also without the ö with the same result.

**Comment by star-buck** [comment]
On last iso, i had no issue connecting to my smb shares. Did it work with
the iso you tested last year or with 19.08?

**Comment by llelectronics** [comment]
Yes it worked before.

**Comment by star-buck** [comment]
With iso from last year? Or 19.08?
What has changed between those?

**Comment by llelectronics** [comment]
19.01 actually. Though 19.08 shows the same behavior. (error message but it mounts fine)
