### ISSUE TITLE
remove 19.08 wallpapers, add new ones and set default to Netrunner Twenty

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#69]
here are new ones:
http://cloud.opendesktop.org/index.php/s/EaCXGizkAfXQgXb

**Comment by llelectronics** [comment]
Added new package here: https://github.com/netrunner-artwork/artwork-wallpapers-netrunner-2001-desktop
@ScarlettGatelyMoore does dci pick this up automatically for 20.01? It has a Netrunner/20.01 branch

**Comment by star-buck** [comment]
remove Netrunner Twenty.jpeg, add this one instead as png and set default:
http://my.opendesktop.org/index.php/s/X59t3wkfJssqej4
