### ISSUE TITLE
the default panel height is too small (30pixels) on lower resolution 1680x1050

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#7]
it should be 48-50px in height:
![Screenshot_20190710_190627](https://user-images.githubusercontent.com/840070/60997262-e9acd600-a345-11e9-8d3c-99c8bc1121e9.png)

the screen res is 1680x1050

**Comment by star-buck** [comment]
it is still this tiny with the resolution of 1680x1050, regardless if installed or live:
![Screenshot_20190727_113214](https://user-images.githubusercontent.com/840070/61992730-32f96700-b062-11e9-80fe-59ac2dd8ea33.png)

**Comment by star-buck** [comment]
maybe ask Marco or anyone else who knows about to handle various resolutions correctly.

**Comment by ScarlettGatelyMoore** [comment]
I think we want to use gridUnit * n rather than hard coding pixel count. I will play around with it tomorrow when it is less late.

**Comment by llelectronics** [comment]
We are setting the size via javascript. It is currently set as follows:
> panel.height = screenGeometry(panel.screen).height > 1024 ? 48 : 37

**Comment by star-buck** [comment]
It doesnt work apparently, so it needs to be fixed somehow differently.

**Comment by llelectronics** [comment]
Switched to gridUnit. This should work now more universal.

**Comment by ScarlettGatelyMoore** [comment]
ok so marco fixed upstream. Will grab the patch and build plasma-workspace on dci

**Comment by star-buck** [comment]
Do we really want to maintain our own plasma-workspace? What happens if
debian updates?

**Comment by star-buck** [comment]
not sure if latest ISO RC shipped it, but still looks exactly the same.

**Comment by llelectronics** [comment]
The latest ISO (20190731.1549) has the fix included. At least the panel size stays the same on my Virtualbox window resize testing. 
https://dci.netrunner.com/view/Images/view/Netrunner%2019.08%20Images/view/Netrunner-Desktop/job/img_desktop_netrunner-desktop_1908_amd64/30/s3/download/netrunner-20190731.1549-amd64.hybrid.iso

**Comment by llelectronics** [comment]
Turns out after installation the panel size is back to 30 pixels for some reason :/

**Comment by star-buck** [comment]
Lets find out why, ask in Blue Channel

**Comment by star-buck** [comment]
yes, it is back to 30pixels here for the resolution given above.
Why cant it simply add a fixed size panel?? Who cares what things look like on high dpi, if those need sclaing anyway, but if the panel scales smart independently, it will look totally stupid afterwards??

**Comment by ScarlettGatelyMoore** [comment]
I just noticed that the commit was done in master and not Netrunner/19.08 so the 19.08 ISO would not have the fix for gridUnit.

**Comment by star-buck** [comment]
How to get this on Netrunner ISO then next?
Since shutdown here still doesnt work properly, was it also not shipped
correctly?

**Comment by llelectronics** [comment]
wontfix for now as we don't want to ship our own Plasma. 
It will be fixed in "next" and we suggested fixes for upstream debian (and plasma).
