### ISSUE TITLE
kvm: current netrunner iso does not start up properly, has apt issues and live config endless timeout

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#70]
- [ ] fix apt error
- [ ] make iso start by fixing live config error:
![Screenshot_20200116_155437](https://user-images.githubusercontent.com/840070/72535316-a2fde280-3878-11ea-925a-b3eec295f934.png)

**Comment by star-buck** [comment]
after some time close to 5 minutes, the boot p continues, but then stuck on a black screen. I cant seem to get it run Plasma Desktop, any of you have the latest ISO running under QEMU/KVM?

**Comment by ScarlettGatelyMoore** [comment]
![image](https://user-images.githubusercontent.com/1056501/72564397-dcc8ec00-386c-11ea-975d-4fba9b8464bc.png)

Boots fine for me. Latest ISO.

http://ds9-eu.s3-website.eu-central-1.amazonaws.com/dci/#!/dci%2Fimages%2F2001%2Famd64%2Fnetrunner-desktop%2Fjobs%2Fimg_desktop_netrunner-desktop_2001_amd64%2F42%2F

That Apt daily gets deactivated here: https://github.com/netrunner-desktop/live-build/blob/master/customization/hooks/live/04-deactivate-apt-daily.hook.chroot

So I am not entirely clear on what happened to your ISO. Is this Desktop?

**Comment by llelectronics** [comment]
Yeah works fine in kvm for me aswell.
