### ISSUE TITLE
Window decorations look broken

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-next#71]
Something looks odd with the window decorations. Inactive ones look fine but active ones on the default background seem to have a few pixels missing on the right.  
![Screenshot_20200128_050731](https://user-images.githubusercontent.com/3415572/73234833-20d0c080-418c-11ea-92c2-529f2c2c4459.png)

**edit:** Ok the effect I describe as odd comes from the 'no border' setting. Setting a border to normal and it looks less odd. 
Anyhow It seems to odd to me. 
Not sure what what you say @star-buck but I would suggest if we go borderless we could maybe stop drawing the icon around the close button which would look imho cleaner by default

![Screenshot_20200128_051541](https://user-images.githubusercontent.com/3415572/73235113-4611fe80-418d-11ea-8642-07e5fc8b0a4f.png)

**Comment by Pointedstick** [comment]
I kinda want to make that little change upstream anyway BTW.
