### ISSUE TITLE
Netrunner 21 XOXO

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#77]
- change all numbers and references to 21 and XOXO
- use this wallpaper:
http://my.opendesktop.org/s/m8xZ9b7CxNymaMH

**Comment by star-buck** [comment]
Please post link to any tested ISO ready with working numbers and wallpaper here in comments.

**Comment by star-buck** [comment]
@llelectronics : Is any ISO done and working?

**Comment by llelectronics** [comment]
DCI failed to build the ISO. We have to take a look at whats wrong with it on monday to be able to build ISOs again.

**Comment by ScarlettGatelyMoore** [comment]
Issue found. Appimagelauncher is being disabled until the dependency line is fixed and updated. I am working on these, but in the meantime I am building ISO without, so everything else can be tested. Will post when this ISO is done building.

**Comment by ScarlettGatelyMoore** [comment]
Removed and yet still installing.. trying to find what else is installing it.

**Comment by llelectronics** [comment]
This ISO (20210127) has all the artwork changes + new kernel (from buster backports) + updated drivers for modern hardware support.
Tested installation on UEFI localized and in english. This worked fine. 
All apps seem to start and work just fine. 
The only thing missing is the appimagelauncher that has issues with our newer kernel apparently. Still we need the newer kernel for modern hardware support as we had several reports of incompatibilities from users in the past for Netrunner 20. 

https://dci.netrunner.com/view/1.%20Netrunner%20Desktop/view/21.01%20Netrunner%20Desktop/view/Snapshot/job/img_netrunner-desktop_2101_amd64/84/s3/download/netrunner-20210127.0604-amd64.hybrid.iso

**Comment by star-buck** [comment]
Any fix to ai launcher?

**Comment by star-buck** [comment]
404 error

**Comment by llelectronics** [comment]
Newest ISO: https://dci.netrunner.com/view/1.%20Netrunner%20Desktop/view/21.01%20Netrunner%20Desktop/view/Snapshot/job/img_netrunner-desktop_2101_amd64/90/s3/download/netrunner-20210129.0546-amd64.hybrid.iso

**Comment by llelectronics** [comment]
One big issue I encountered is that modern intel laptops boot now with the new kernel but don't have any sound output as Debian does not ship the intel sof firmware for those newer sound chips. (bullseye has a package for it but apparently not buster)
We have to find a way to either deactivate the intel sof driver (which results in newer laptops having sound output but no mic input support) or backporting the sof driver to gain full sound support.

**Comment by star-buck** [comment]
If you encouter any bugs, please go ahead and add a ticket for it with
description, solution suggestion etc.

That is for this issue and also appimagelauncher.

**Comment by llelectronics** [comment]
The new ISO here https://dci.netrunner.com/view/1.%20Netrunner%20Desktop/view/21.01%20Netrunner%20Desktop/view/Snapshot/job/img_netrunner-desktop_2101_amd64/93/s3/download/netrunner-20210131.0122-amd64.hybrid.iso
provides the fix for the Intel sound card issue I mentioned.

**Comment by llelectronics** [comment]
New ISO working with appimagelauncher: https://dci.netrunner.com/view/1.%20Netrunner%20Desktop/view/21.01%20Netrunner%20Desktop/view/Snapshot/job/img_netrunner-desktop_2101_amd64/110/s3/download/netrunner-20210212.1921-amd64.hybrid.iso

**Comment by llelectronics** [comment]
I uploaded the final version to our old download server. It needs uploading to sourceforge where I don't have the credentials to:
http://pub.netrunner.com/netrunner-desktop-2101-64bit.iso
