### ISSUE TITLE
simple menu doesnt work?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#81]
as claimed here:
https://www.youtube.com/watch?v=QP7ReR3KQbA&t=2m50s

**Comment by llelectronics** [comment]
Yes saw it and already fixed with some reverts here: https://github.com/dci-extras-packaging/simplemenu/commit/6d731ff30824338bf051e06ea2fc685a9ae8331a
It needs building the package and updating the repo.

**Comment by llelectronics** [comment]
Fix landed as update in the repos.
