### ISSUE TITLE
Suggestions for Calamares configuration

### ISSUE THREAD

**Issue by adriaandegroot** [blue-systems/netrunner-next#84]
When started from a console (e.g. in konsole or xterm), Calamares prints warnings for issues that it finds in the configuration files, and sometimes suggests changes -- or it says how it interprets the configuration. It's useful to take a look at the warnings occasionally: for one thing because some of those warnings are slated to change to errors (blocking startup) at some point in the future.

- `branding.desc` is missing three keys; Calamares fills in something reasonable, but you might add
  ```
  windowPlacement: free
  sidebar: widget,left
  navigation: widget,bottom
  ```
  just to get it to shut up.
- `welcome.conf` is missing a URL to check for internet connectivity. You may specify one or more URLs, but it defaults to `example.com`. This works, since that domain is guaranteed to exist, but again, you can make it explicit (or change to `netrunner.com` to double-check that the OS domain is reachable)
- There's no `locale.conf`; while all the defaults are reasonable, Calamares complains that the file is missing entirely. You can set the module to `noconfig` (in the module descriptor) or add the file. In particular, it might be nice to set `useSystemTimezone` to true if the ISO does not default to America/NewYork as timezone.
- There's no `keyboard.conf`; same comments apply. You might set `writeEtcDefaultKeyboard: true` just to get it to shut up.

(All of this is really low-priority: it's just to reduce warnings from Calamares itself, and if any of it actually **breaks**, you'll notice it anyway)

**Comment by llelectronics** [comment]
Thanks for the suggestions. I added everything in now. See:
https://github.com/netrunner-desktop/calamares-desktop/commit/f36d73924c6240fbf7d63b27e10cd960ca8a8e99
https://github.com/netrunner-desktop/calamares-desktop/commit/f95c127f1b9b9abe8d4dc1162ba386a99db1e401
https://github.com/netrunner-desktop/calamares-desktop/commit/c389e9591e9f52f5269756974b174c7e5bed4f24
