### ISSUE TITLE
15-minute QA 2022.04.08-08.21

### ISSUE THREAD

**Issue by adriaandegroot** [blue-systems/netrunner-next#86]
## Test Setup

- VirtualBox (on FreeBSD, not that that should matter)
- 32 GB virtual HDD, BIOS

## Noted Issues

Live ISO:

- Boots to GRUB menu, "Netrunner 22" and "Netrunner 22 (something)", which is fine
- [x] live session has no wallpaper: just a black background. The wallpaper configuration points to `/usr/share/wallpapers/netrunner-desktop-22/` which isn't present on the ISO.
- Installation with *erase disk* via Calamares was successful.

Installed system:

- Boots to GRUB menu, "Netrunner Desktop 22" and "Netrunner 22 (something)"
- There's a slightly weird plymouth-ish graphical display during boot with a Debian wallpaper?
- [x] installed session has no wallpaper: just a black background.

**Comment by adriaandegroot** [comment]
## Test Setup (2)

- VirtualBox
- 16 GB virtual HDD, EFI

## Noted Issues

- Starts in 1024x768 (this may be a VBox issue more than anything else)
- Doesn't offer to install alongside an XFS-root-based distro
- Replaced a partition
- [ ] After reboot, drops to a GRUB> prompt

**Comment by adriaandegroot** [comment]
Suggestion: add `-D6` to the command in `calamares.desktop` (so it reads `pkexec /usr/bin/calamares -D6`) so that logging is more complete. In older Calamares, both console and log-file use the same setting; since 3.2.54 or so the log-file is always verbose, and the `-D` flag controls only console-logging. Since Netrunner uses older Cala, you need the `-D6` to get decent log-files for reporting.

**Comment by Justinzobel** [comment]
Have added the `-D6` parameter and building an ISO now.

**Comment by adriaandegroot** [comment]
This is fixed on the 04.20, 04.22 and 04.24 ISOs I tried, so closing.
