### ISSUE TITLE
N23: todos

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#90]
- [ ] this **dhcpcd** issue has not been fixed, it is absolutely the same as before:
system after installation is completely overloaded (load averages of 3.x), heater fans are spinning even when doing nothing after log in...
![Screenshot_20220816_121406](https://user-images.githubusercontent.com/840070/184855412-297575d4-6f5b-4a83-b4aa-936982e2ce3c.png)

**Comment by star-buck** [comment]
after burning iso to usb via etcher, the usb name still reads Netrunner 22 (at least when using etcher again after burning latest N23 iso and picking the same usb drive that it was burnt to from the list shown in etcher, it doesnt get shown at all in KDE Dolphin sidebar sadly)

**Comment by UriHerrera** [comment]
Latest image with fixes: https://pub.netrunner.com/.testing/netrunner-next-amd64_2022.10.27-21.12.iso

- `dhcpcd` is no longer in the default installation as nothing requires it. NetworkManager uses `dhclient` for using DHCP.
- The ISO image now has the correct label (see fig. 1)

![image](https://user-images.githubusercontent.com/3053525/198403938-b9e79a51-871f-4eec-8290-c75b0f0aa4dc.png)
> fig. 1 ISO label in Dolphin
