### ISSUE TITLE
apt sources.list WHY DOES IT READ AND LINK TO NETRUNNER-22 ???

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#96]

**Comment by UriHerrera** [comment]
That's the [Suite](https://wiki.debian.org/DebianRepository/Format#Suite) and [Codenames](https://wiki.debian.org/DebianRepository/Format#Codename) used when the repository was set up. I can't configure or change that.

All Netrunner packages are uploaded to that repository. There are no new or additional repositories setup for this purpose.

**Comment by ScarlettGatelyMoore** [comment]
You need to create a new aptly database for each new release and name it the appropriate release. Justin should be able to help. Unsubscribing!

**Comment by Justinzobel** [comment]
Netrunner 24 repo created: http://repo.netrunner.com/netrunner24/

Apt sources line needs to now be: `deb http://repo.netrunner.com/netrunner24 netrunner24 netrunner24`

And all packages that we manage that aren't in Debian's repository need to be rebuilt in that repo against whichever Debian release Netrunner 24 will be using.
